on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

- name: Set up JDK
  uses: actions/setup-java@v3
  with:
    java-version: '17' # Specify the Java version you're using
    distribution: 'temurin'

- name: Build Docker Image
  run: docker build -t my-app .
  
- name: Build with Maven
  run: mvn clean install

- name: Cache Maven packages
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-
